const DATA=[
{name:"Caser MIMAscota RC",price:"47 €/año",priceMonth:"≈ 3,92 €/mes",type:"rc",ppp:true,health:false,age:true,url:"https://www.caser.es/seguros-de-mascotas/responsabilidad-civil-perros",facts:["RC hasta 350.000 €","Defensa jurídica y fianzas","PPP: 98 €/año según Caser"]},
{name:"Caser MIMAscota Plan Salud",price:"19,40 €/mes",type:"health",ppp:true,health:true,age:true,url:"https://www.caser.es/seguros-de-mascotas/perros",facts:["RC hasta 350.000 €","Consultas y revisiones incluidas según modalidad","Caser indica sin carencia"]},
{name:"Caser MIMAscota Plan Salud Premium",price:"27,50 €/mes",type:"both",ppp:true,health:true,age:true,url:"https://www.caser.es/seguros-de-mascotas/perros",facts:["RC hasta 350.000 €","Prevención ampliada","Caser indica que asegura todas las edades y razas"]},
{name:"Caser WeCAN Check",price:"232 €/año",type:"health",ppp:true,health:true,age:true,url:"https://www.caser.es/seguros-de-mascotas/seguro-veterinario-wecan-check",facts:["Perros y gatos de cualquier edad","Sin carencia según Caser","Cuadro veterinario y videollamada"]}];
const cards=document.getElementById('results');
function render(filter=null){cards.innerHTML='';let arr=DATA.slice();if(filter){arr.sort((a,b)=>score(b,filter)-score(a,filter))}arr.forEach((x,i)=>{let el=document.createElement('article');el.className='result '+(i===0&&filter?'recommended':'');el.innerHTML=(i===0&&filter?'<span class="badge">MEJOR ENCAJE PARA TI</span>':'')+`<h3>${x.name}</h3><div class="price">${x.price}</div><ul>${x.facts.map(f=>`<li>${f}</li>`).join('')}</ul><a class="official" href="${x.url}" target="_blank" rel="noopener">Ver en la web oficial →</a>`;cards.appendChild(el)})}
function score(x,f){let s=0;if(f.need==='rc'&&x.type==='rc')s+=5;if(f.need==='health'&&x.health)s+=5;if(f.need==='both'&&x.type==='both')s+=6;if(f.ppp==='yes'&&x.ppp)s+=2;if(f.age==='senior'&&x.age)s+=2;if(f.budget==='low'&&parseFloat(x.price.replace(',','.'))<=10)s+=3;if(f.budget==='mid'&&parseFloat(x.price.replace(',','.'))<=25)s+=3;if(f.budget==='high')s+=1;return s}
document.getElementById('finder').addEventListener('submit',e=>{e.preventDefault();const f={age:age.value,need:need.value,ppp:ppp.value,budget:budget.value};let best=DATA.slice().sort((a,b)=>score(b,f)-score(a,f))[0];let advice=f.need==='rc'?'Tu prioridad es la responsabilidad civil. Compara especialmente capital, defensa jurídica y precio.':f.need==='health'?'Tu prioridad son los gastos/servicios veterinarios. Mira límites, carencias, red veterinaria, reembolsos y exclusiones.':'Buscas una protección más amplia. Compara RC y salud por separado para no confundir coberturas.';if(f.age==='senior')advice+=' Además, revisa expresamente la edad de contratación y renovación.';if(f.ppp==='yes')advice+=' Para PPP, comprueba el precio y requisitos específicos de RC.';document.getElementById('output').innerHTML=`<h3>Tu punto de partida: ${best.name}</h3><p>${advice}</p><p><strong>Importante:</strong> esto no significa que sea el mejor seguro para ti; es un filtro automático basado en los criterios que has indicado.</p>`;document.getElementById('output').hidden=false;render(f)});
render();