
const products=[
{name:"Caser MIMAscota RC",price:"Desde 3,90 €/mes",rc:"Hasta 350.000 €",health:"No",fit:"RC",url:"https://www.caser.es/seguros-de-mascotas/responsabilidad-civil-perros"},
{name:"Caser MIMAscota Plan Salud",price:"Desde 19,40 €/mes",rc:"Hasta 350.000 €",health:"Servicios de salud según modalidad",fit:"Salud + RC",url:"https://www.caser.es/seguros-de-mascotas/perros"},
{name:"Caser MIMAscota Premium",price:"Desde 27,50 €/mes",rc:"Hasta 350.000 €",health:"Cobertura ampliada según modalidad",fit:"Salud amplia + RC",url:"https://www.caser.es/seguros-de-mascotas/perros"},
{name:"Caser WeCAN RC",price:"47 €/año",rc:"Hasta 350.000 €",health:"No",fit:"RC",url:"https://www.caser.es/seguros-de-mascotas/responsabilidad-civil-perros"}
];
function render(list=products){const el=document.querySelector("#results");if(!el)return;el.innerHTML=list.map(p=>`<article class="result"><span class="pill">${p.fit}</span><h3>${p.name}</h3><div class="price">${p.price}</div><ul><li>RC: ${p.rc}</li><li>Veterinario: ${p.health}</li></ul><a class="btn" target="_blank" rel="nofollow sponsored" href="${p.url}">Ver información oficial →</a></article>`).join("")}
render();
const form=document.querySelector("#finder");
if(form)form.addEventListener("submit",e=>{e.preventDefault();const age=document.querySelector("#age").value,need=document.querySelector("#need").value,ppp=document.querySelector("#ppp").value,budget=document.querySelector("#budget").value;let list=[...products];if(need==="rc")list=list.filter(p=>p.fit.includes("RC"));if(need==="health")list=list.filter(p=>p.fit.includes("Salud"));if(budget==="low")list=list.filter(p=>p.price.includes("3,90")||p.price.includes("47"));if(ppp==="yes")list=list.filter(p=>p.rc.includes("350.000"));if(!list.length)list=products;render(list);const out=document.querySelector("#output");out.hidden=false;out.innerHTML=`<strong>Orientación:</strong> ${need==="rc"?"empieza comparando RC y capital asegurado.":need==="health"?"prioriza límites, red/reembolso, carencias y exclusiones.":"compara RC y asistencia veterinaria por separado."} ${age==="senior"?"En perros senior, revisa especialmente la edad de aceptación y renovación.":""} ${ppp==="yes"?"Para PPP, comprueba requisitos específicos y el capital de RC.":""}`;document.querySelector("#comparador").scrollIntoView({behavior:"smooth"})});
